import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import YAML from "yaml";
import { describe, expect, it } from "vitest";
import {
  deriveSliceStatus,
  detectDependencyCycles,
  parseSliceTasksMarkdown,
  rollupChange,
  rollupSlice,
} from "../src/lib/sliceRollup.js";

async function tempChange(): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), "weave-slice-rollup-"));
  await mkdir(path.join(root, "task-slices", "01-alpha"), { recursive: true });
  await mkdir(path.join(root, "task-slices", "02-beta"), { recursive: true });
  return root;
}

const sliceTasks = `---
artifact: tasks
slice: 01-alpha
---

# Tasks: Alpha

## Active Task Index

| ID | Status | Execution | Repos | Owner | Title | Blocked by |
| --- | --- | --- | --- | --- | --- | --- |
| T1 | done | hitl | weave-it | | First | None |
| T2 | in_progress | hitl | weave-it | | Second | T1 |

## weave-it

### T1: First

Status: done
Repos: weave-it
Execution: hitl
Blocked by: None

### T2: Second

Status: in_progress
Repos: weave-it
Execution: hitl
Blocked by: T1
`;

describe("sliceRollup", () => {
  it("parses task statuses and derives slice status", () => {
    const parsed = parseSliceTasksMarkdown(sliceTasks);
    expect(parsed.parsed).toBe(true);
    expect(parsed.total).toBe(2);
    expect(parsed.done).toBe(1);
    expect(parsed.blocked).toBe(0);
    expect(deriveSliceStatus(parsed.statuses)).toBe("in_progress");
  });

  it("leaves task_summary unchanged when tasks.md does not parse", async () => {
    const changePath = await tempChange();
    const slicePath = path.join(changePath, "task-slices", "01-alpha");
    await writeFile(
      path.join(slicePath, "status.yml"),
      YAML.stringify({
        version: 1,
        id: "01-alpha",
        title: "Alpha",
        status: "pending",
        owner: "",
        repos: [],
        depends_on: [],
        task_summary: { total: 5, done: 2, blocked: 0 },
        created_at: "2026-06-09T00:00:00.000Z",
        updated_at: "2026-06-09T00:00:00.000Z",
      }),
    );
    await writeFile(path.join(slicePath, "tasks.md"), "# broken\n\nno task index");

    const result = await rollupSlice(slicePath);
    expect(result.metadata.task_summary).toEqual({ total: 5, done: 2, blocked: 0 });
    expect(result.metadata.status).toBe("pending");
  });

  it("rolls up slice status and regenerates dependency graph", async () => {
    const changePath = await tempChange();
    const alphaPath = path.join(changePath, "task-slices", "01-alpha");
    const betaPath = path.join(changePath, "task-slices", "02-beta");

    await writeFile(path.join(alphaPath, "tasks.md"), sliceTasks);
    await writeFile(
      path.join(alphaPath, "status.yml"),
      YAML.stringify({
        version: 1,
        id: "01-alpha",
        title: "Alpha",
        status: "pending",
        owner: "",
        repos: [],
        depends_on: [],
        task_summary: { total: 0, done: 0, blocked: 0 },
        created_at: "2026-06-09T00:00:00.000Z",
        updated_at: "2026-06-09T00:00:00.000Z",
      }),
    );

    await writeFile(
      path.join(betaPath, "tasks.md"),
      sliceTasks.replace(/done/g, "todo").replace(/in_progress/g, "todo"),
    );
    await writeFile(
      path.join(betaPath, "status.yml"),
      YAML.stringify({
        version: 1,
        id: "02-beta",
        title: "Beta",
        status: "pending",
        owner: "",
        repos: [],
        depends_on: ["01-alpha"],
        task_summary: { total: 0, done: 0, blocked: 0 },
        created_at: "2026-06-09T00:00:00.000Z",
        updated_at: "2026-06-09T00:00:00.000Z",
      }),
    );

    const result = await rollupChange({ changePath, check: true });
    expect(result.status).toBe("check_failed");
    expect(result.dependencyGraphPath).toContain("dependency-graph.md");

    const applied = await rollupChange({ changePath });
    expect(applied.status).toBe("ok");
    const alphaStatus = YAML.parse(await readFile(path.join(alphaPath, "status.yml"), "utf8"));
    expect(alphaStatus.status).toBe("in_progress");
    expect(alphaStatus.task_summary).toEqual({ total: 2, done: 1, blocked: 0 });

    const graph = await readFile(path.join(changePath, "task-slices", "dependency-graph.md"), "utf8");
    expect(graph).toContain("AUTO-GENERATED by weave slice rollup");
    expect(graph).toContain("02-beta");
    expect(graph).toContain("blocked");
  });

  it("detects dependency cycles", () => {
    const cycles = detectDependencyCycles([
      {
        version: 1,
        id: "01-a",
        title: "A",
        status: "pending",
        owner: "",
        repos: [],
        depends_on: ["02-b"],
        task_summary: { total: 0, done: 0, blocked: 0 },
        updated_at: "2026-06-09T00:00:00.000Z",
      },
      {
        version: 1,
        id: "02-b",
        title: "B",
        status: "pending",
        owner: "",
        repos: [],
        depends_on: ["01-a"],
        task_summary: { total: 0, done: 0, blocked: 0 },
        updated_at: "2026-06-09T00:00:00.000Z",
      },
    ]);
    expect(cycles).not.toBeNull();
    expect(cycles?.length).toBeGreaterThan(0);
  });
});
